spring:
  datasource:
    username: orderuser
    password: password
    url: jdbc:mysql://127.0.0.1:3306/orderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  flyway:
    user: orderadmin
    password: password
  sql:
    init:
      mode: always